/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as rootRouteRouteImport } from './routes/(root)/route'
import { Route as authSigninRouteImport } from './routes/(auth)/signin'
import { Route as rootAccountsRouteImport } from './routes/(root)/accounts'
import { Route as rootAdaptersRouteImport } from './routes/(root)/adapters'
import { Route as rootAuditRouteImport } from './routes/(root)/audit'
import { Route as rootEntitlementRouteImport } from './routes/(root)/entitlement'
import { Route as rootOverviewRouteImport } from './routes/(root)/overview'
import { Route as rootWorkersRouteImport } from './routes/(root)/workers'
import { Route as rootUsersIndexRouteImport } from './routes/(root)/users/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const rootRouteRoute = rootRouteRouteImport.update({
  id: '/(root)',
  getParentRoute: () => rootRouteImport,
} as any)
const authSigninRoute = authSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => authRouteRoute,
} as any)
const rootAccountsRoute = rootAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteRoute,
} as any)
const rootAdaptersRoute = rootAdaptersRouteImport.update({
  id: '/adapters',
  path: '/adapters',
  getParentRoute: () => rootRouteRoute,
} as any)
const rootAuditRoute = rootAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteRoute,
} as any)
const rootEntitlementRoute = rootEntitlementRouteImport.update({
  id: '/entitlement',
  path: '/entitlement',
  getParentRoute: () => rootRouteRoute,
} as any)
const rootOverviewRoute = rootOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => rootRouteRoute,
} as any)
const rootWorkersRoute = rootWorkersRouteImport.update({
  id: '/workers',
  path: '/workers',
  getParentRoute: () => rootRouteRoute,
} as any)
const rootUsersIndexRoute = rootUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/signin': typeof authSigninRoute
  '/accounts': typeof rootAccountsRoute
  '/adapters': typeof rootAdaptersRoute
  '/audit': typeof rootAuditRoute
  '/entitlement': typeof rootEntitlementRoute
  '/overview': typeof rootOverviewRoute
  '/workers': typeof rootWorkersRoute
  '/users/': typeof rootUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signin': typeof authSigninRoute
  '/accounts': typeof rootAccountsRoute
  '/adapters': typeof rootAdaptersRoute
  '/audit': typeof rootAuditRoute
  '/entitlement': typeof rootEntitlementRoute
  '/overview': typeof rootOverviewRoute
  '/workers': typeof rootWorkersRoute
  '/users': typeof rootUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)': typeof authRouteRouteWithChildren
  '/(root)': typeof rootRouteRouteWithChildren
  '/(auth)/signin': typeof authSigninRoute
  '/(root)/accounts': typeof rootAccountsRoute
  '/(root)/adapters': typeof rootAdaptersRoute
  '/(root)/audit': typeof rootAuditRoute
  '/(root)/entitlement': typeof rootEntitlementRoute
  '/(root)/overview': typeof rootOverviewRoute
  '/(root)/workers': typeof rootWorkersRoute
  '/(root)/users/': typeof rootUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signin'
    | '/accounts'
    | '/adapters'
    | '/audit'
    | '/entitlement'
    | '/overview'
    | '/workers'
    | '/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signin'
    | '/accounts'
    | '/adapters'
    | '/audit'
    | '/entitlement'
    | '/overview'
    | '/workers'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/(auth)'
    | '/(root)'
    | '/(auth)/signin'
    | '/(root)/accounts'
    | '/(root)/adapters'
    | '/(root)/audit'
    | '/(root)/entitlement'
    | '/(root)/overview'
    | '/(root)/workers'
    | '/(root)/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authRouteRoute: typeof authRouteRouteWithChildren
  rootRouteRoute: typeof rootRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(root)': {
      id: '/(root)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof rootRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/signin': {
      id: '/(auth)/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof authSigninRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(root)/accounts': {
      id: '/(root)/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof rootAccountsRouteImport
      parentRoute: typeof rootRouteRoute
    }
    '/(root)/adapters': {
      id: '/(root)/adapters'
      path: '/adapters'
      fullPath: '/adapters'
      preLoaderRoute: typeof rootAdaptersRouteImport
      parentRoute: typeof rootRouteRoute
    }
    '/(root)/audit': {
      id: '/(root)/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof rootAuditRouteImport
      parentRoute: typeof rootRouteRoute
    }
    '/(root)/entitlement': {
      id: '/(root)/entitlement'
      path: '/entitlement'
      fullPath: '/entitlement'
      preLoaderRoute: typeof rootEntitlementRouteImport
      parentRoute: typeof rootRouteRoute
    }
    '/(root)/overview': {
      id: '/(root)/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof rootOverviewRouteImport
      parentRoute: typeof rootRouteRoute
    }
    '/(root)/workers': {
      id: '/(root)/workers'
      path: '/workers'
      fullPath: '/workers'
      preLoaderRoute: typeof rootWorkersRouteImport
      parentRoute: typeof rootRouteRoute
    }
    '/(root)/users/': {
      id: '/(root)/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof rootUsersIndexRouteImport
      parentRoute: typeof rootRouteRoute
    }
  }
}

interface authRouteRouteChildren {
  authSigninRoute: typeof authSigninRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authSigninRoute: authSigninRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface rootRouteRouteChildren {
  rootAccountsRoute: typeof rootAccountsRoute
  rootAdaptersRoute: typeof rootAdaptersRoute
  rootAuditRoute: typeof rootAuditRoute
  rootEntitlementRoute: typeof rootEntitlementRoute
  rootOverviewRoute: typeof rootOverviewRoute
  rootWorkersRoute: typeof rootWorkersRoute
  rootUsersIndexRoute: typeof rootUsersIndexRoute
}

const rootRouteRouteChildren: rootRouteRouteChildren = {
  rootAccountsRoute: rootAccountsRoute,
  rootAdaptersRoute: rootAdaptersRoute,
  rootAuditRoute: rootAuditRoute,
  rootEntitlementRoute: rootEntitlementRoute,
  rootOverviewRoute: rootOverviewRoute,
  rootWorkersRoute: rootWorkersRoute,
  rootUsersIndexRoute: rootUsersIndexRoute,
}

const rootRouteRouteWithChildren = rootRouteRoute._addFileChildren(
  rootRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRouteRoute: authRouteRouteWithChildren,
  rootRouteRoute: rootRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
