CREATE TABLE chat_messages (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT NOT NULL,
  account_id BIGINT NULL,
  account_public_id CHAR(26) NOT NULL DEFAULT '',
  friend_id BIGINT NULL,
  friend_display_name VARCHAR(128) NOT NULL DEFAULT '',
  direction ENUM('in','out') NOT NULL DEFAULT 'in',
  msg_type VARCHAR(32) NOT NULL DEFAULT 'unknown',
  body TEXT NOT NULL,
  body_hash CHAR(64) NOT NULL DEFAULT '',
  platform_msg_id VARCHAR(128) NULL,
  time_bucket DATETIME NULL,
  media_url VARCHAR(1024) NOT NULL DEFAULT '',
  media_object_key VARCHAR(512) NOT NULL DEFAULT '',
  source VARCHAR(32) NOT NULL DEFAULT '',
  observed_at DATETIME NOT NULL,
  review_flag VARCHAR(16) NOT NULL DEFAULT 'none',
  reviewed_by BIGINT NULL,
  reviewed_at DATETIME NULL,
  created_at DATETIME NOT NULL,
  KEY idx_chat_user_time (user_id, observed_at),
  KEY idx_chat_account (account_id),
  CONSTRAINT fk_chat_user FOREIGN KEY (user_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
