-- Douyin Keeper Next - schema-v1.sql
-- PostgreSQL 17+
-- public_id values are generated by application code.

CREATE TABLE users (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  public_id UUID NOT NULL UNIQUE,
  role TEXT NOT NULL DEFAULT 'user' CHECK (role IN ('user', 'admin')),
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'disabled')),
  display_name TEXT NOT NULL DEFAULT '',
  timezone TEXT NOT NULL DEFAULT 'Asia/Shanghai',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_at TIMESTAMPTZ
);

CREATE TABLE auth_identities (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  provider TEXT NOT NULL CHECK (provider IN ('local','wechat_mini')),
  provider_subject TEXT NOT NULL,
  credential_hash TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(provider, provider_subject),
  CHECK ((provider = 'local' AND credential_hash IS NOT NULL)
      OR (provider = 'wechat_mini' AND credential_hash IS NULL))
);

CREATE INDEX ix_auth_identities_user ON auth_identities(user_id);

CREATE TABLE auth_sessions (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  public_id UUID NOT NULL UNIQUE,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  client_type TEXT NOT NULL CHECK (client_type IN ('web','mini','admin')),
  expires_at TIMESTAMPTZ NOT NULL,
  last_seen_at TIMESTAMPTZ,
  revoked_at TIMESTAMPTZ,
  revoke_reason TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CHECK (expires_at > created_at)
);

CREATE INDEX ix_auth_sessions_user_active
  ON auth_sessions(user_id, expires_at)
  WHERE revoked_at IS NULL;

CREATE TABLE auth_refresh_tokens (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  session_id BIGINT NOT NULL REFERENCES auth_sessions(id) ON DELETE CASCADE,
  token_hash BYTEA NOT NULL UNIQUE,
  expires_at TIMESTAMPTZ NOT NULL,
  used_at TIMESTAMPTZ,
  revoked_at TIMESTAMPTZ,
  replaced_by_id BIGINT REFERENCES auth_refresh_tokens(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CHECK (expires_at > created_at)
);

CREATE INDEX ix_auth_refresh_tokens_session
  ON auth_refresh_tokens(session_id, created_at DESC);

CREATE TABLE auth_link_codes (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  public_id UUID NOT NULL UNIQUE,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  code_hash BYTEA NOT NULL UNIQUE,
  code_fingerprint TEXT NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  consumed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CHECK (expires_at > created_at)
);

CREATE INDEX ix_auth_link_codes_user_active
  ON auth_link_codes(user_id, expires_at)
  WHERE consumed_at IS NULL;

CREATE TABLE entitlement_plans (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  public_id UUID NOT NULL UNIQUE,
  code TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active','disabled')),
  account_quota INTEGER NOT NULL CHECK (account_quota >= 0),
  task_quota INTEGER NOT NULL CHECK (task_quota >= 0),
  daily_send_quota INTEGER NOT NULL CHECK (daily_send_quota >= 0),
  features_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE card_batches (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  public_id UUID NOT NULL UNIQUE,
  entitlement_plan_id BIGINT NOT NULL REFERENCES entitlement_plans(id),
  name TEXT NOT NULL,
  duration_days INTEGER NOT NULL CHECK (duration_days > 0 AND duration_days <= 3660),
  quantity INTEGER NOT NULL CHECK (quantity > 0),
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active','disabled')),
  code_version INTEGER NOT NULL DEFAULT 1 CHECK (code_version > 0),
  redeem_not_before TIMESTAMPTZ,
  redeem_before TIMESTAMPTZ,
  created_by BIGINT NOT NULL REFERENCES users(id),
  note TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CHECK (redeem_before IS NULL OR redeem_not_before IS NULL OR redeem_before > redeem_not_before)
);

CREATE TABLE card_codes (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  batch_id BIGINT NOT NULL REFERENCES card_batches(id) ON DELETE RESTRICT,
  code_hash BYTEA NOT NULL UNIQUE,
  code_fingerprint TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'unused' CHECK (status IN ('unused','redeemed','revoked')),
  redeemed_by BIGINT REFERENCES users(id),
  redeemed_at TIMESTAMPTZ,
  revoked_at TIMESTAMPTZ,
  revoked_by BIGINT REFERENCES users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CHECK (
    (status = 'unused' AND redeemed_by IS NULL AND redeemed_at IS NULL AND revoked_at IS NULL)
    OR (status = 'redeemed' AND redeemed_by IS NOT NULL AND redeemed_at IS NOT NULL AND revoked_at IS NULL)
    OR (status = 'revoked' AND redeemed_by IS NULL AND redeemed_at IS NULL AND revoked_at IS NOT NULL)
  )
);

CREATE INDEX ix_card_codes_batch_status ON card_codes(batch_id, status);

CREATE TABLE entitlement_grants (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  public_id UUID NOT NULL UNIQUE,
  user_id BIGINT NOT NULL REFERENCES users(id),
  entitlement_plan_id BIGINT NOT NULL REFERENCES entitlement_plans(id),
  source_type TEXT NOT NULL CHECK (source_type IN ('card','admin')),
  source_card_id BIGINT UNIQUE REFERENCES card_codes(id),
  starts_at TIMESTAMPTZ NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  revoked_at TIMESTAMPTZ,
  revoked_by BIGINT REFERENCES users(id),
  revoke_reason TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CHECK (expires_at > starts_at),
  CHECK ((source_type = 'card' AND source_card_id IS NOT NULL)
      OR (source_type = 'admin' AND source_card_id IS NULL))
);

CREATE INDEX ix_entitlement_grants_user_time
  ON entitlement_grants(user_id, starts_at, expires_at)
  WHERE revoked_at IS NULL;

CREATE TABLE entitlement_daily_usage (
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  local_date DATE NOT NULL,
  reserved_send_count INTEGER NOT NULL DEFAULT 0 CHECK (reserved_send_count >= 0),
  succeeded_send_count INTEGER NOT NULL DEFAULT 0 CHECK (succeeded_send_count >= 0),
  failed_send_count INTEGER NOT NULL DEFAULT 0 CHECK (failed_send_count >= 0),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY(user_id, local_date)
);

CREATE TABLE douyin_accounts (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  public_id UUID NOT NULL UNIQUE,
  user_id BIGINT NOT NULL REFERENCES users(id),
  platform_user_id TEXT,
  nickname TEXT NOT NULL DEFAULT '',
  avatar_url TEXT,
  binding_status TEXT NOT NULL DEFAULT 'unbound' CHECK (binding_status IN ('unbound','binding','bound','released')),
  session_status TEXT NOT NULL DEFAULT 'unknown' CHECK (session_status IN ('unknown','valid','expired','challenge_required')),
  risk_status TEXT NOT NULL DEFAULT 'normal' CHECK (risk_status IN ('normal','cooling_down','paused')),
  paused_at TIMESTAMPTZ,
  cooldown_until TIMESTAMPTZ,
  last_session_check_at TIMESTAMPTZ,
  last_friend_sync_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_at TIMESTAMPTZ
);

CREATE UNIQUE INDEX ux_douyin_account_user_platform ON douyin_accounts(user_id, platform_user_id)
  WHERE platform_user_id IS NOT NULL AND deleted_at IS NULL;
CREATE INDEX ix_douyin_accounts_user ON douyin_accounts(user_id) WHERE deleted_at IS NULL;

CREATE TABLE account_sessions (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  account_id BIGINT NOT NULL REFERENCES douyin_accounts(id) ON DELETE CASCADE,
  version INTEGER NOT NULL,
  key_version INTEGER NOT NULL,
  cipher_alg TEXT NOT NULL DEFAULT 'AES-256-GCM',
  ciphertext BYTEA NOT NULL,
  aad_version INTEGER NOT NULL DEFAULT 1,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  last_validated_at TIMESTAMPTZ,
  revoked_at TIMESTAMPTZ,
  UNIQUE(account_id, version)
);

CREATE UNIQUE INDEX ux_account_sessions_active ON account_sessions(account_id) WHERE revoked_at IS NULL;

CREATE TABLE friends (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  public_id UUID NOT NULL UNIQUE,
  account_id BIGINT NOT NULL REFERENCES douyin_accounts(id) ON DELETE CASCADE,
  platform_user_id TEXT,
  identity_status TEXT NOT NULL DEFAULT 'pending' CHECK (identity_status IN ('pending','resolved','ambiguous','missing')),
  display_name TEXT NOT NULL DEFAULT '',
  nickname TEXT NOT NULL DEFAULT '',
  short_id TEXT,
  avatar_url TEXT,
  streak_days INTEGER NOT NULL DEFAULT 0 CHECK (streak_days >= 0),
  has_conversation BOOLEAN NOT NULL DEFAULT false,
  spark_enabled BOOLEAN NOT NULL DEFAULT false,
  last_seen_at TIMESTAMPTZ,
  last_sent_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_at TIMESTAMPTZ
);

CREATE UNIQUE INDEX ux_friend_account_platform ON friends(account_id, platform_user_id)
  WHERE platform_user_id IS NOT NULL AND deleted_at IS NULL;
CREATE INDEX ix_friends_account_active ON friends(account_id, spark_enabled) WHERE deleted_at IS NULL;

CREATE TABLE conversations (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  public_id UUID NOT NULL UNIQUE,
  account_id BIGINT NOT NULL REFERENCES douyin_accounts(id) ON DELETE CASCADE,
  friend_id BIGINT NOT NULL REFERENCES friends(id) ON DELETE CASCADE,
  platform_conversation_id TEXT NOT NULL,
  channel TEXT NOT NULL CHECK (channel IN ('consumer','creator')),
  last_message_at TIMESTAMPTZ,
  last_synced_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(account_id, platform_conversation_id),
  UNIQUE(account_id, friend_id, channel)
);

CREATE TABLE spark_tasks (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  public_id UUID NOT NULL UNIQUE,
  user_id BIGINT NOT NULL REFERENCES users(id),
  account_id BIGINT NOT NULL REFERENCES douyin_accounts(id) ON DELETE CASCADE,
  friend_id BIGINT NOT NULL REFERENCES friends(id) ON DELETE CASCADE,
  enabled BOOLEAN NOT NULL DEFAULT true,
  timezone TEXT NOT NULL DEFAULT 'Asia/Shanghai',
  window_start TIME NOT NULL,
  window_end TIME NOT NULL,
  message_kind TEXT NOT NULL DEFAULT 'text' CHECK (message_kind IN ('text','sticker')),
  message_body TEXT,
  allow_first_message BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_at TIMESTAMPTZ,
  CHECK (window_start < window_end),
  CHECK ((message_kind <> 'text') OR message_body IS NOT NULL)
);

CREATE UNIQUE INDEX ux_task_account_friend ON spark_tasks(account_id, friend_id) WHERE deleted_at IS NULL;
CREATE INDEX ix_task_scheduler ON spark_tasks(enabled, account_id) WHERE deleted_at IS NULL;

CREATE TABLE send_intents (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  public_id UUID NOT NULL UNIQUE,
  intent_type TEXT NOT NULL CHECK (intent_type IN ('scheduled','manual')),
  request_id UUID,
  task_id BIGINT REFERENCES spark_tasks(id) ON DELETE SET NULL,
  account_id BIGINT NOT NULL REFERENCES douyin_accounts(id),
  friend_id BIGINT NOT NULL REFERENCES friends(id),
  local_date DATE,
  scheduled_at TIMESTAMPTZ NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending','queued','running','retry_wait','succeeded','failed','skipped','cancelled')),
  error_code TEXT,
  next_attempt_at TIMESTAMPTZ,
  last_job_id BIGINT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CHECK ((intent_type = 'scheduled' AND task_id IS NOT NULL AND local_date IS NOT NULL)
      OR (intent_type = 'manual' AND request_id IS NOT NULL))
);

CREATE UNIQUE INDEX ux_send_intent_scheduled ON send_intents(task_id, local_date) WHERE intent_type = 'scheduled';
CREATE UNIQUE INDEX ux_send_intent_manual_request ON send_intents(request_id) WHERE intent_type = 'manual';
CREATE INDEX ix_send_intent_due ON send_intents(status, scheduled_at, next_attempt_at);

CREATE TABLE send_jobs (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  public_id UUID NOT NULL UNIQUE,
  intent_id BIGINT NOT NULL REFERENCES send_intents(id) ON DELETE CASCADE,
  account_id BIGINT NOT NULL REFERENCES douyin_accounts(id),
  friend_id BIGINT NOT NULL REFERENCES friends(id),
  attempt INTEGER NOT NULL CHECK (attempt >= 1),
  selected_adapter TEXT,
  status TEXT NOT NULL DEFAULT 'queued' CHECK (status IN ('queued','running','succeeded','failed','cancelled')),
  error_code TEXT,
  retryable BOOLEAN NOT NULL DEFAULT false,
  platform_message_id TEXT,
  worker_id TEXT,
  heartbeat_at TIMESTAMPTZ,
  lease_expires_at TIMESTAMPTZ,
  started_at TIMESTAMPTZ,
  finished_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(intent_id, attempt)
);

ALTER TABLE send_intents ADD CONSTRAINT fk_send_intent_last_job
  FOREIGN KEY (last_job_id) REFERENCES send_jobs(id) DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX ix_send_jobs_account_created ON send_jobs(account_id, created_at DESC);
CREATE INDEX ix_send_jobs_lease ON send_jobs(status, lease_expires_at) WHERE status = 'running';

CREATE TABLE jobs (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  public_id UUID NOT NULL UNIQUE,
  user_id BIGINT REFERENCES users(id),
  account_id BIGINT REFERENCES douyin_accounts(id),
  type TEXT NOT NULL,
  status TEXT NOT NULL CHECK (status IN ('queued','running','waiting_user','succeeded','failed','cancelled')),
  error_code TEXT,
  cancelable BOOLEAN NOT NULL DEFAULT false,
  cancel_requested_at TIMESTAMPTZ,
  worker_id TEXT,
  heartbeat_at TIMESTAMPTZ,
  lease_expires_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  started_at TIMESTAMPTZ,
  finished_at TIMESTAMPTZ
);

CREATE INDEX ix_jobs_lease ON jobs(status, lease_expires_at)
  WHERE status IN ('running','waiting_user');

CREATE TABLE job_events (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  job_id BIGINT NOT NULL REFERENCES jobs(id) ON DELETE CASCADE,
  seq BIGINT NOT NULL,
  event_type TEXT NOT NULL,
  payload_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(job_id, seq)
);

CREATE TABLE queue_outbox (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  public_id UUID NOT NULL UNIQUE,
  kind TEXT NOT NULL,
  aggregate_type TEXT NOT NULL,
  aggregate_id TEXT NOT NULL,
  payload_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','publishing','published','dead')),
  available_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  attempts INTEGER NOT NULL DEFAULT 0 CHECK (attempts >= 0),
  next_attempt_at TIMESTAMPTZ,
  dedupe_key TEXT NOT NULL UNIQUE,
  locked_by TEXT,
  locked_until TIMESTAMPTZ,
  last_error_code TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  published_at TIMESTAMPTZ
);

CREATE INDEX ix_queue_outbox_publish
  ON queue_outbox(status, available_at, next_attempt_at)
  WHERE status IN ('pending','publishing');

CREATE TABLE capability_snapshots (
  account_id BIGINT NOT NULL REFERENCES douyin_accounts(id) ON DELETE CASCADE,
  capability TEXT NOT NULL,
  status TEXT NOT NULL CHECK (status IN ('available','degraded','unavailable','unknown')),
  adapter TEXT,
  error_code TEXT,
  checked_at TIMESTAMPTZ NOT NULL,
  PRIMARY KEY(account_id, capability)
);

CREATE TABLE adapter_health (
  adapter TEXT PRIMARY KEY,
  status TEXT NOT NULL CHECK (status IN ('healthy','degraded','open','disabled')),
  version TEXT,
  error_code TEXT,
  failure_count INTEGER NOT NULL DEFAULT 0,
  circuit_open_until TIMESTAMPTZ,
  checked_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE risk_events (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  public_id UUID NOT NULL UNIQUE,
  account_id BIGINT NOT NULL REFERENCES douyin_accounts(id) ON DELETE CASCADE,
  category TEXT NOT NULL CHECK (category IN ('AUTH','PLATFORM','PROTOCOL','BROWSER','NETWORK','DATA')),
  code TEXT NOT NULL,
  severity TEXT NOT NULL CHECK (severity IN ('info','warning','critical')),
  source_adapter TEXT,
  detail_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  action TEXT,
  cooldown_until TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX ix_risk_account_created ON risk_events(account_id, created_at DESC);

CREATE TABLE audit_logs (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  actor_user_id BIGINT REFERENCES users(id),
  action TEXT NOT NULL,
  resource_type TEXT NOT NULL,
  resource_id TEXT,
  request_id UUID,
  ip_hash TEXT,
  detail_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE site_settings (
  key TEXT PRIMARY KEY,
  value_json JSONB NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
