/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as rootRouteRouteImport } from './routes/(root)/route'
import { Route as authSigninRouteImport } from './routes/(auth)/signin'
import { Route as authSignupRouteImport } from './routes/(auth)/signup'
import { Route as rootAccountsRouteImport } from './routes/(root)/accounts'
import { Route as rootDashboardRouteImport } from './routes/(root)/dashboard'
import { Route as rootEntitlementRouteImport } from './routes/(root)/entitlement'
import { Route as rootFriendsRouteImport } from './routes/(root)/friends'
import { Route as rootHistoryRouteImport } from './routes/(root)/history'
import { Route as rootTasksRouteImport } from './routes/(root)/tasks'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const rootRouteRoute = rootRouteRouteImport.update({
  id: '/(root)',
  getParentRoute: () => rootRouteImport,
} as any)
const authSigninRoute = authSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => authRouteRoute,
} as any)
const authSignupRoute = authSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => authRouteRoute,
} as any)
const rootAccountsRoute = rootAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteRoute,
} as any)
const rootDashboardRoute = rootDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteRoute,
} as any)
const rootEntitlementRoute = rootEntitlementRouteImport.update({
  id: '/entitlement',
  path: '/entitlement',
  getParentRoute: () => rootRouteRoute,
} as any)
const rootFriendsRoute = rootFriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => rootRouteRoute,
} as any)
const rootHistoryRoute = rootHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteRoute,
} as any)
const rootTasksRoute = rootTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/signin': typeof authSigninRoute
  '/signup': typeof authSignupRoute
  '/accounts': typeof rootAccountsRoute
  '/dashboard': typeof rootDashboardRoute
  '/entitlement': typeof rootEntitlementRoute
  '/friends': typeof rootFriendsRoute
  '/history': typeof rootHistoryRoute
  '/tasks': typeof rootTasksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signin': typeof authSigninRoute
  '/signup': typeof authSignupRoute
  '/accounts': typeof rootAccountsRoute
  '/dashboard': typeof rootDashboardRoute
  '/entitlement': typeof rootEntitlementRoute
  '/friends': typeof rootFriendsRoute
  '/history': typeof rootHistoryRoute
  '/tasks': typeof rootTasksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)': typeof authRouteRouteWithChildren
  '/(root)': typeof rootRouteRouteWithChildren
  '/(auth)/signin': typeof authSigninRoute
  '/(auth)/signup': typeof authSignupRoute
  '/(root)/accounts': typeof rootAccountsRoute
  '/(root)/dashboard': typeof rootDashboardRoute
  '/(root)/entitlement': typeof rootEntitlementRoute
  '/(root)/friends': typeof rootFriendsRoute
  '/(root)/history': typeof rootHistoryRoute
  '/(root)/tasks': typeof rootTasksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signin'
    | '/signup'
    | '/accounts'
    | '/dashboard'
    | '/entitlement'
    | '/friends'
    | '/history'
    | '/tasks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signin'
    | '/signup'
    | '/accounts'
    | '/dashboard'
    | '/entitlement'
    | '/friends'
    | '/history'
    | '/tasks'
  id:
    | '__root__'
    | '/'
    | '/(auth)'
    | '/(root)'
    | '/(auth)/signin'
    | '/(auth)/signup'
    | '/(root)/accounts'
    | '/(root)/dashboard'
    | '/(root)/entitlement'
    | '/(root)/friends'
    | '/(root)/history'
    | '/(root)/tasks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authRouteRoute: typeof authRouteRouteWithChildren
  rootRouteRoute: typeof rootRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(root)': {
      id: '/(root)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof rootRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/signin': {
      id: '/(auth)/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof authSigninRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(root)/accounts': {
      id: '/(root)/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof rootAccountsRouteImport
      parentRoute: typeof rootRouteRoute
    }
    '/(root)/dashboard': {
      id: '/(root)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof rootDashboardRouteImport
      parentRoute: typeof rootRouteRoute
    }
    '/(root)/entitlement': {
      id: '/(root)/entitlement'
      path: '/entitlement'
      fullPath: '/entitlement'
      preLoaderRoute: typeof rootEntitlementRouteImport
      parentRoute: typeof rootRouteRoute
    }
    '/(root)/friends': {
      id: '/(root)/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof rootFriendsRouteImport
      parentRoute: typeof rootRouteRoute
    }
    '/(root)/history': {
      id: '/(root)/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof rootHistoryRouteImport
      parentRoute: typeof rootRouteRoute
    }
    '/(root)/tasks': {
      id: '/(root)/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof rootTasksRouteImport
      parentRoute: typeof rootRouteRoute
    }
  }
}

interface authRouteRouteChildren {
  authSigninRoute: typeof authSigninRoute
  authSignupRoute: typeof authSignupRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authSigninRoute: authSigninRoute,
  authSignupRoute: authSignupRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface rootRouteRouteChildren {
  rootAccountsRoute: typeof rootAccountsRoute
  rootDashboardRoute: typeof rootDashboardRoute
  rootEntitlementRoute: typeof rootEntitlementRoute
  rootFriendsRoute: typeof rootFriendsRoute
  rootHistoryRoute: typeof rootHistoryRoute
  rootTasksRoute: typeof rootTasksRoute
}

const rootRouteRouteChildren: rootRouteRouteChildren = {
  rootAccountsRoute: rootAccountsRoute,
  rootDashboardRoute: rootDashboardRoute,
  rootEntitlementRoute: rootEntitlementRoute,
  rootFriendsRoute: rootFriendsRoute,
  rootHistoryRoute: rootHistoryRoute,
  rootTasksRoute: rootTasksRoute,
}

const rootRouteRouteWithChildren = rootRouteRoute._addFileChildren(
  rootRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRouteRoute: authRouteRouteWithChildren,
  rootRouteRoute: rootRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
