/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as rootRouteRouteImport } from './routes/(root)/route'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as authSigninRouteImport } from './routes/(auth)/signin'
import { Route as authSignupRouteImport } from './routes/(auth)/signup'
import { Route as rootAccountsRouteImport } from './routes/(root)/accounts'
import { Route as rootConversationsRouteImport } from './routes/(root)/conversations'
import { Route as rootDashboardRouteImport } from './routes/(root)/dashboard'
import { Route as rootEntitlementRouteImport } from './routes/(root)/entitlement'
import { Route as rootFriendsRouteImport } from './routes/(root)/friends'
import { Route as rootHistoryRouteImport } from './routes/(root)/history'
import { Route as rootNotificationsRouteImport } from './routes/(root)/notifications'
import { Route as rootTasksRouteImport } from './routes/(root)/tasks'
import { Route as rootTemplatesRouteImport } from './routes/(root)/templates'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAccountsRouteImport } from './routes/admin/accounts'
import { Route as AdminAdaptersRouteImport } from './routes/admin/adapters'
import { Route as AdminAuditRouteImport } from './routes/admin/audit'
import { Route as AdminEntitlementRouteImport } from './routes/admin/entitlement'
import { Route as AdminRisksRouteImport } from './routes/admin/risks'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminWorkersRouteImport } from './routes/admin/workers'
import { Route as AdminUsersUserIdRouteImport } from './routes/admin/users/$userId'
import { Route as AdminEntitlementBatchesBatchIdRouteImport } from './routes/admin/entitlement/batches/$batchId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const rootRouteRoute = rootRouteRouteImport.update({
  id: '/(root)',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const authSigninRoute = authSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => authRouteRoute,
} as any)
const authSignupRoute = authSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => authRouteRoute,
} as any)
const rootAccountsRoute = rootAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteRoute,
} as any)
const rootConversationsRoute = rootConversationsRouteImport.update({
  id: '/conversations',
  path: '/conversations',
  getParentRoute: () => rootRouteRoute,
} as any)
const rootDashboardRoute = rootDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteRoute,
} as any)
const rootEntitlementRoute = rootEntitlementRouteImport.update({
  id: '/entitlement',
  path: '/entitlement',
  getParentRoute: () => rootRouteRoute,
} as any)
const rootFriendsRoute = rootFriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => rootRouteRoute,
} as any)
const rootHistoryRoute = rootHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteRoute,
} as any)
const rootNotificationsRoute = rootNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteRoute,
} as any)
const rootTasksRoute = rootTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteRoute,
} as any)
const rootTemplatesRoute = rootTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAccountsRoute = AdminAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdaptersRoute = AdminAdaptersRouteImport.update({
  id: '/adapters',
  path: '/adapters',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEntitlementRoute = AdminEntitlementRouteImport.update({
  id: '/entitlement',
  path: '/entitlement',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRisksRoute = AdminRisksRouteImport.update({
  id: '/risks',
  path: '/risks',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWorkersRoute = AdminWorkersRouteImport.update({
  id: '/workers',
  path: '/workers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersUserIdRoute = AdminUsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => AdminUsersRoute,
} as any)
const AdminEntitlementBatchesBatchIdRoute =
  AdminEntitlementBatchesBatchIdRouteImport.update({
    id: '/batches/$batchId',
    path: '/batches/$batchId',
    getParentRoute: () => AdminEntitlementRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/signin': typeof authSigninRoute
  '/signup': typeof authSignupRoute
  '/accounts': typeof rootAccountsRoute
  '/conversations': typeof rootConversationsRoute
  '/dashboard': typeof rootDashboardRoute
  '/entitlement': typeof rootEntitlementRoute
  '/friends': typeof rootFriendsRoute
  '/history': typeof rootHistoryRoute
  '/notifications': typeof rootNotificationsRoute
  '/tasks': typeof rootTasksRoute
  '/templates': typeof rootTemplatesRoute
  '/admin/accounts': typeof AdminAccountsRoute
  '/admin/adapters': typeof AdminAdaptersRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/entitlement': typeof AdminEntitlementRouteWithChildren
  '/admin/risks': typeof AdminRisksRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/admin/workers': typeof AdminWorkersRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/admin/entitlement/batches/$batchId': typeof AdminEntitlementBatchesBatchIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signin': typeof authSigninRoute
  '/signup': typeof authSignupRoute
  '/accounts': typeof rootAccountsRoute
  '/conversations': typeof rootConversationsRoute
  '/dashboard': typeof rootDashboardRoute
  '/entitlement': typeof rootEntitlementRoute
  '/friends': typeof rootFriendsRoute
  '/history': typeof rootHistoryRoute
  '/notifications': typeof rootNotificationsRoute
  '/tasks': typeof rootTasksRoute
  '/templates': typeof rootTemplatesRoute
  '/admin/accounts': typeof AdminAccountsRoute
  '/admin/adapters': typeof AdminAdaptersRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/entitlement': typeof AdminEntitlementRouteWithChildren
  '/admin/risks': typeof AdminRisksRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/admin/workers': typeof AdminWorkersRoute
  '/admin': typeof AdminIndexRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/admin/entitlement/batches/$batchId': typeof AdminEntitlementBatchesBatchIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)': typeof authRouteRouteWithChildren
  '/(root)': typeof rootRouteRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/(auth)/signin': typeof authSigninRoute
  '/(auth)/signup': typeof authSignupRoute
  '/(root)/accounts': typeof rootAccountsRoute
  '/(root)/conversations': typeof rootConversationsRoute
  '/(root)/dashboard': typeof rootDashboardRoute
  '/(root)/entitlement': typeof rootEntitlementRoute
  '/(root)/friends': typeof rootFriendsRoute
  '/(root)/history': typeof rootHistoryRoute
  '/(root)/notifications': typeof rootNotificationsRoute
  '/(root)/tasks': typeof rootTasksRoute
  '/(root)/templates': typeof rootTemplatesRoute
  '/admin/accounts': typeof AdminAccountsRoute
  '/admin/adapters': typeof AdminAdaptersRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/entitlement': typeof AdminEntitlementRouteWithChildren
  '/admin/risks': typeof AdminRisksRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/admin/workers': typeof AdminWorkersRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/admin/entitlement/batches/$batchId': typeof AdminEntitlementBatchesBatchIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/signin'
    | '/signup'
    | '/accounts'
    | '/conversations'
    | '/dashboard'
    | '/entitlement'
    | '/friends'
    | '/history'
    | '/notifications'
    | '/tasks'
    | '/templates'
    | '/admin/accounts'
    | '/admin/adapters'
    | '/admin/audit'
    | '/admin/entitlement'
    | '/admin/risks'
    | '/admin/users'
    | '/admin/workers'
    | '/admin/'
    | '/admin/users/$userId'
    | '/admin/entitlement/batches/$batchId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signin'
    | '/signup'
    | '/accounts'
    | '/conversations'
    | '/dashboard'
    | '/entitlement'
    | '/friends'
    | '/history'
    | '/notifications'
    | '/tasks'
    | '/templates'
    | '/admin/accounts'
    | '/admin/adapters'
    | '/admin/audit'
    | '/admin/entitlement'
    | '/admin/risks'
    | '/admin/users'
    | '/admin/workers'
    | '/admin'
    | '/admin/users/$userId'
    | '/admin/entitlement/batches/$batchId'
  id:
    | '__root__'
    | '/'
    | '/(auth)'
    | '/(root)'
    | '/admin'
    | '/(auth)/signin'
    | '/(auth)/signup'
    | '/(root)/accounts'
    | '/(root)/conversations'
    | '/(root)/dashboard'
    | '/(root)/entitlement'
    | '/(root)/friends'
    | '/(root)/history'
    | '/(root)/notifications'
    | '/(root)/tasks'
    | '/(root)/templates'
    | '/admin/accounts'
    | '/admin/adapters'
    | '/admin/audit'
    | '/admin/entitlement'
    | '/admin/risks'
    | '/admin/users'
    | '/admin/workers'
    | '/admin/'
    | '/admin/users/$userId'
    | '/admin/entitlement/batches/$batchId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authRouteRoute: typeof authRouteRouteWithChildren
  rootRouteRoute: typeof rootRouteRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(root)': {
      id: '/(root)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof rootRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/signin': {
      id: '/(auth)/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof authSigninRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(root)/accounts': {
      id: '/(root)/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof rootAccountsRouteImport
      parentRoute: typeof rootRouteRoute
    }
    '/(root)/conversations': {
      id: '/(root)/conversations'
      path: '/conversations'
      fullPath: '/conversations'
      preLoaderRoute: typeof rootConversationsRouteImport
      parentRoute: typeof rootRouteRoute
    }
    '/(root)/dashboard': {
      id: '/(root)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof rootDashboardRouteImport
      parentRoute: typeof rootRouteRoute
    }
    '/(root)/entitlement': {
      id: '/(root)/entitlement'
      path: '/entitlement'
      fullPath: '/entitlement'
      preLoaderRoute: typeof rootEntitlementRouteImport
      parentRoute: typeof rootRouteRoute
    }
    '/(root)/friends': {
      id: '/(root)/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof rootFriendsRouteImport
      parentRoute: typeof rootRouteRoute
    }
    '/(root)/history': {
      id: '/(root)/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof rootHistoryRouteImport
      parentRoute: typeof rootRouteRoute
    }
    '/(root)/notifications': {
      id: '/(root)/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof rootNotificationsRouteImport
      parentRoute: typeof rootRouteRoute
    }
    '/(root)/tasks': {
      id: '/(root)/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof rootTasksRouteImport
      parentRoute: typeof rootRouteRoute
    }
    '/(root)/templates': {
      id: '/(root)/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof rootTemplatesRouteImport
      parentRoute: typeof rootRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/accounts': {
      id: '/admin/accounts'
      path: '/accounts'
      fullPath: '/admin/accounts'
      preLoaderRoute: typeof AdminAccountsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/adapters': {
      id: '/admin/adapters'
      path: '/adapters'
      fullPath: '/admin/adapters'
      preLoaderRoute: typeof AdminAdaptersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/entitlement': {
      id: '/admin/entitlement'
      path: '/entitlement'
      fullPath: '/admin/entitlement'
      preLoaderRoute: typeof AdminEntitlementRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/risks': {
      id: '/admin/risks'
      path: '/risks'
      fullPath: '/admin/risks'
      preLoaderRoute: typeof AdminRisksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/workers': {
      id: '/admin/workers'
      path: '/workers'
      fullPath: '/admin/workers'
      preLoaderRoute: typeof AdminWorkersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users/$userId': {
      id: '/admin/users/$userId'
      path: '/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminUsersUserIdRouteImport
      parentRoute: typeof AdminUsersRoute
    }
    '/admin/entitlement/batches/$batchId': {
      id: '/admin/entitlement/batches/$batchId'
      path: '/batches/$batchId'
      fullPath: '/admin/entitlement/batches/$batchId'
      preLoaderRoute: typeof AdminEntitlementBatchesBatchIdRouteImport
      parentRoute: typeof AdminEntitlementRoute
    }
  }
}

interface authRouteRouteChildren {
  authSigninRoute: typeof authSigninRoute
  authSignupRoute: typeof authSignupRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authSigninRoute: authSigninRoute,
  authSignupRoute: authSignupRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface rootRouteRouteChildren {
  rootAccountsRoute: typeof rootAccountsRoute
  rootConversationsRoute: typeof rootConversationsRoute
  rootDashboardRoute: typeof rootDashboardRoute
  rootEntitlementRoute: typeof rootEntitlementRoute
  rootFriendsRoute: typeof rootFriendsRoute
  rootHistoryRoute: typeof rootHistoryRoute
  rootNotificationsRoute: typeof rootNotificationsRoute
  rootTasksRoute: typeof rootTasksRoute
  rootTemplatesRoute: typeof rootTemplatesRoute
}

const rootRouteRouteChildren: rootRouteRouteChildren = {
  rootAccountsRoute: rootAccountsRoute,
  rootConversationsRoute: rootConversationsRoute,
  rootDashboardRoute: rootDashboardRoute,
  rootEntitlementRoute: rootEntitlementRoute,
  rootFriendsRoute: rootFriendsRoute,
  rootHistoryRoute: rootHistoryRoute,
  rootNotificationsRoute: rootNotificationsRoute,
  rootTasksRoute: rootTasksRoute,
  rootTemplatesRoute: rootTemplatesRoute,
}

const rootRouteRouteWithChildren = rootRouteRoute._addFileChildren(
  rootRouteRouteChildren,
)

interface AdminEntitlementRouteChildren {
  AdminEntitlementBatchesBatchIdRoute: typeof AdminEntitlementBatchesBatchIdRoute
}

const AdminEntitlementRouteChildren: AdminEntitlementRouteChildren = {
  AdminEntitlementBatchesBatchIdRoute: AdminEntitlementBatchesBatchIdRoute,
}

const AdminEntitlementRouteWithChildren =
  AdminEntitlementRoute._addFileChildren(AdminEntitlementRouteChildren)

interface AdminUsersRouteChildren {
  AdminUsersUserIdRoute: typeof AdminUsersUserIdRoute
}

const AdminUsersRouteChildren: AdminUsersRouteChildren = {
  AdminUsersUserIdRoute: AdminUsersUserIdRoute,
}

const AdminUsersRouteWithChildren = AdminUsersRoute._addFileChildren(
  AdminUsersRouteChildren,
)

interface AdminRouteChildren {
  AdminAccountsRoute: typeof AdminAccountsRoute
  AdminAdaptersRoute: typeof AdminAdaptersRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminEntitlementRoute: typeof AdminEntitlementRouteWithChildren
  AdminRisksRoute: typeof AdminRisksRoute
  AdminUsersRoute: typeof AdminUsersRouteWithChildren
  AdminWorkersRoute: typeof AdminWorkersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAccountsRoute: AdminAccountsRoute,
  AdminAdaptersRoute: AdminAdaptersRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminEntitlementRoute: AdminEntitlementRouteWithChildren,
  AdminRisksRoute: AdminRisksRoute,
  AdminUsersRoute: AdminUsersRouteWithChildren,
  AdminWorkersRoute: AdminWorkersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRouteRoute: authRouteRouteWithChildren,
  rootRouteRoute: rootRouteRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
