import type { components } from '@douyin-keeper/sdk-ts'
import { Link } from '@tanstack/react-router'
import { Badge, Button, Input, Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@douyin-keeper/ui-web'
import { useState } from 'react'

type Plan = components['schemas']['AdminEntitlementPlan']
type Batch = components['schemas']['AdminCardBatch']
type Redemption = components['schemas']['AdminRedemption']
type CardCode = components['schemas']['AdminCardCode']

export function AdminPlanTable({ plans, pendingPlanId, onDisable }: { plans: Plan[]; pendingPlanId?: string; onDisable: (id: string) => void }) {
  return <div className="overflow-x-auto rounded-lg border bg-card"><Table><TableHeader><TableRow><TableHead className="pl-5">方案</TableHead><TableHead>配额</TableHead><TableHead>迁移权重</TableHead><TableHead>功能</TableHead><TableHead>状态</TableHead><TableHead className="pr-5">操作</TableHead></TableRow></TableHeader><TableBody>{plans.map((plan) => <TableRow key={plan.id}><TableCell className="min-w-48 pl-5"><div className="font-medium">{plan.name}</div><div className="mt-1 text-xs text-muted-foreground">{plan.code}</div></TableCell><TableCell className="min-w-48 text-sm"><div>账号 {plan.account_quota} · 任务 {plan.task_quota}</div><div className="mt-1 text-xs text-muted-foreground">每日发送 {plan.daily_send_quota}</div></TableCell><TableCell className="min-w-24 text-sm"><div className="font-medium">{plan.migration_weight}</div><div className="mt-1 text-xs text-muted-foreground">能力单位/天</div></TableCell><TableCell className="min-w-52"><div className="flex max-w-64 flex-wrap gap-1.5">{Object.entries(plan.features).filter(([, enabled]) => enabled).slice(0, 4).map(([feature]) => <Badge key={feature} variant="muted">{feature}</Badge>)}{!Object.values(plan.features).some(Boolean) && <span className="text-sm text-muted-foreground">无额外功能</span>}</div></TableCell><TableCell className="min-w-24"><Badge variant={plan.status === 'active' ? 'success' : 'muted'}>{plan.status === 'active' ? '启用' : '已停用'}</Badge></TableCell><TableCell className="min-w-24 pr-5">{plan.status === 'active' ? <Button size="sm" variant="ghost" disabled={pendingPlanId === plan.id} onClick={() => onDisable(plan.id)}>{pendingPlanId === plan.id ? '处理中…' : '停用'}</Button> : <span className="text-sm text-muted-foreground">—</span>}</TableCell></TableRow>)}</TableBody></Table></div>
}

export function AdminBatchTable({ batches, pendingBatchId, onDisable }: { batches: Batch[]; pendingBatchId?: string; onDisable: (id: string) => void }) {
  return <div className="overflow-x-auto rounded-lg border bg-card"><Table><TableHeader><TableRow><TableHead className="pl-5">批次 / 方案</TableHead><TableHead>使用情况</TableHead><TableHead>兑换窗口</TableHead><TableHead>创建人</TableHead><TableHead>状态</TableHead><TableHead className="pr-5">操作</TableHead></TableRow></TableHeader><TableBody>{batches.map((batch) => <TableRow key={batch.id}><TableCell className="min-w-52 pl-5"><Link to="/admin/entitlement/batches/$batchId" params={{ batchId: batch.id }} className="font-medium hover:underline">{batch.name}</Link><div className="mt-1 text-xs text-muted-foreground">{batch.plan_name} · {batch.duration_days} 天</div></TableCell><TableCell className="min-w-48 text-sm"><div>已兑换 {batch.redeemed_count} / {batch.quantity}</div><div className="mt-1 text-xs text-muted-foreground">未使用 {batch.unused_count} · 撤销 {batch.revoked_count} · {formatRate(batch.redemption_rate)}</div></TableCell><TableCell className="min-w-48 text-sm"><div>{formatDate(batch.redeem_not_before)} 起</div><div className="mt-1 text-xs text-muted-foreground">{batch.redeem_before ? `截止 ${formatDate(batch.redeem_before)}` : '无截止时间'}</div></TableCell><TableCell className="min-w-28 text-sm">{batch.created_by_display_name}</TableCell><TableCell className="min-w-24"><Badge variant={batch.status === 'active' ? 'success' : 'muted'}>{batch.status === 'active' ? '启用' : '已停用'}</Badge></TableCell><TableCell className="min-w-24 pr-5">{batch.status === 'active' ? <Button size="sm" variant="ghost" disabled={pendingBatchId === batch.id} onClick={() => onDisable(batch.id)}>{pendingBatchId === batch.id ? '处理中…' : '停用'}</Button> : <span className="text-sm text-muted-foreground">—</span>}</TableCell></TableRow>)}</TableBody></Table></div>
}

export function AdminRedemptionTable({ redemptions }: { redemptions: Redemption[] }) {
  return <div className="overflow-x-auto rounded-lg border bg-card"><Table><TableHeader><TableRow><TableHead className="pl-5">用户</TableHead><TableHead>方案 / 来源</TableHead><TableHead>有效期</TableHead><TableHead>卡密指纹</TableHead><TableHead className="pr-5">状态</TableHead></TableRow></TableHeader><TableBody>{redemptions.map((item) => <TableRow key={item.id}><TableCell className="min-w-40 pl-5"><div className="font-medium">{item.user_display_name}</div><div className="mt-1 max-w-44 truncate text-xs text-muted-foreground" title={item.user_id}>{item.user_id}</div></TableCell><TableCell className="min-w-36"><div className="font-medium">{item.plan_name}</div><div className="mt-1 text-xs text-muted-foreground">{item.source_type === 'card' ? '卡密兑换' : '管理员授权'} · {item.plan_code}</div></TableCell><TableCell className="min-w-48 text-sm"><div>{formatDate(item.starts_at)} —</div><div className="mt-1 text-xs text-muted-foreground">{formatDate(item.expires_at)}</div></TableCell><TableCell className="min-w-32 font-mono text-xs text-muted-foreground">{item.code_fingerprint ?? '—'}</TableCell><TableCell className="min-w-32 pr-5"><Badge variant={statusVariant(item.status)}>{statusLabel(item.status)}</Badge>{item.revoke_reason && <div className="mt-1 max-w-40 truncate text-xs text-muted-foreground" title={item.revoke_reason}>原因：{item.revoke_reason}</div>}</TableCell></TableRow>)}</TableBody></Table></div>
}

export function AdminUserGrantTable({ grants, pendingGrantId, onRevoke }: { grants: Redemption[]; pendingGrantId?: string; onRevoke: (id: string, reason: string) => void }) {
  const [reasons, setReasons] = useState<Record<string, string>>({})
  return <div className="overflow-x-auto rounded-lg border bg-card"><Table><TableHeader><TableRow><TableHead className="pl-5">方案 / 来源</TableHead><TableHead>有效期</TableHead><TableHead>状态</TableHead><TableHead>卡密指纹</TableHead><TableHead className="pr-5">操作</TableHead></TableRow></TableHeader><TableBody>{grants.map((item) => <TableRow key={item.id}><TableCell className="min-w-40 pl-5"><div className="font-medium">{item.plan_name}</div><div className="mt-1 text-xs text-muted-foreground">{item.source_type === 'card' ? '卡密兑换' : '管理员授权'} · {item.plan_code}</div></TableCell><TableCell className="min-w-48 text-sm"><div>{formatDate(item.starts_at)} —</div><div className="mt-1 text-xs text-muted-foreground">{formatDate(item.expires_at)}</div></TableCell><TableCell className="min-w-28"><Badge variant={statusVariant(item.status)}>{statusLabel(item.status)}</Badge>{item.revoke_reason && <div className="mt-1 max-w-36 truncate text-xs text-muted-foreground" title={item.revoke_reason}>{item.revoke_reason}</div>}</TableCell><TableCell className="min-w-36 font-mono text-xs text-muted-foreground">{item.code_fingerprint ?? '—'}</TableCell><TableCell className="min-w-64 pr-5">{item.status !== 'revoked' && item.status !== 'expired' ? <div className="flex items-center gap-2"><Input aria-label={`撤销原因 ${item.id}`} value={reasons[item.id] ?? ''} onChange={(event) => setReasons((current) => ({ ...current, [item.id]: event.target.value }))} placeholder="撤销原因" /><Button size="sm" variant="ghost" disabled={!reasons[item.id]?.trim() || pendingGrantId === item.id} onClick={() => onRevoke(item.id, reasons[item.id].trim())}>{pendingGrantId === item.id ? '处理中…' : '撤销'}</Button></div> : <span className="text-sm text-muted-foreground">—</span>}</TableCell></TableRow>)}</TableBody></Table></div>
}

export function AdminCardCodeTable({ codes, pendingCodeId, onRevoke }: { codes: CardCode[]; pendingCodeId?: number; onRevoke: (id: number, reason: string) => void }) {
  const [reasons, setReasons] = useState<Record<string, string>>({})
  return <div className="overflow-x-auto rounded-lg border bg-card"><Table><TableHeader><TableRow><TableHead className="pl-5">卡密指纹</TableHead><TableHead>状态</TableHead><TableHead>时间</TableHead><TableHead className="pr-5">操作</TableHead></TableRow></TableHeader><TableBody>{codes.map((item) => <TableRow key={item.id}><TableCell className="min-w-48 pl-5 font-mono text-xs">{item.code_fingerprint}</TableCell><TableCell className="min-w-24"><Badge variant={item.status === 'unused' ? 'secondary' : item.status === 'redeemed' ? 'success' : 'muted'}>{item.status === 'unused' ? '未使用' : item.status === 'redeemed' ? '已兑换' : '已撤销'}</Badge></TableCell><TableCell className="min-w-48 text-sm"><div>创建 {formatDate(item.created_at)}</div><div className="mt-1 text-xs text-muted-foreground">{item.redeemed_at ? `兑换 ${formatDate(item.redeemed_at)}` : item.revoked_at ? `撤销 ${formatDate(item.revoked_at)}` : '尚未使用'}</div></TableCell><TableCell className="min-w-64 pr-5">{item.status === 'unused' ? <div className="flex items-center gap-2"><Input aria-label={`卡密撤销原因 ${item.id}`} value={reasons[String(item.id)] ?? ''} onChange={(event) => setReasons((current) => ({ ...current, [String(item.id)]: event.target.value }))} placeholder="撤销原因" /><Button size="sm" variant="ghost" disabled={!reasons[String(item.id)]?.trim() || pendingCodeId === item.id} onClick={() => onRevoke(item.id, reasons[String(item.id)].trim())}>{pendingCodeId === item.id ? '处理中…' : '撤销'}</Button></div> : <span className="text-sm text-muted-foreground">—</span>}</TableCell></TableRow>)}</TableBody></Table></div>
}

export function AdminGrantCreateForm({ plans, pending, disabled, onSubmit }: { plans: Plan[]; pending: boolean; disabled?: boolean; onSubmit: (value: components['schemas']['AdminCreateEntitlementGrantRequest']) => void }) {
  return <form className="grid gap-3 sm:grid-cols-[1fr_0.7fr_auto]" onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); onSubmit({ plan_id: String(form.get('plan_id') ?? ''), duration_days: Number(form.get('duration_days') ?? 0) }) }}><select name="plan_id" aria-label="授权方案" className="h-9 rounded-md border border-input bg-transparent px-3 text-sm" required defaultValue="" disabled={disabled}><option value="" disabled>选择权益方案</option>{plans.filter((plan) => plan.status === 'active').map((plan) => <option key={plan.id} value={plan.id}>{plan.name} · {plan.code}</option>)}</select><Input name="duration_days" aria-label="授权天数" type="number" min="1" max="3660" placeholder="天数" required disabled={disabled} /><Button type="submit" disabled={disabled || pending || plans.every((plan) => plan.status !== 'active')}>{pending ? '授权中…' : '人工授权'}</Button></form>
}

export function PlanCreateForm({ pending, onSubmit }: { pending: boolean; onSubmit: (value: components['schemas']['AdminCreateEntitlementPlanRequest']) => void }) {
  return <form className="grid gap-3 md:grid-cols-[1fr_1fr_0.7fr_0.7fr_0.9fr_0.8fr_auto]" onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); onSubmit({ code: String(form.get('code') ?? '').trim(), name: String(form.get('name') ?? '').trim(), account_quota: Number(form.get('account_quota') ?? 0), task_quota: Number(form.get('task_quota') ?? 0), daily_send_quota: Number(form.get('daily_send_quota') ?? 0), migration_weight: Number(form.get('migration_weight') ?? 1), features: { browser_text_send: form.get('browser_text_send') === 'on' } }) }}><Input name="code" aria-label="方案代码" placeholder="方案代码，例如 standard" required /><Input name="name" aria-label="方案名称" placeholder="方案名称" required /><Input name="account_quota" aria-label="账号额度" type="number" min="0" placeholder="账号" required /><Input name="task_quota" aria-label="任务额度" type="number" min="0" placeholder="任务" required /><Input name="daily_send_quota" aria-label="每日发送额度" type="number" min="0" placeholder="每日发送" required /><Input name="migration_weight" aria-label="迁移权重" type="number" min="1" max="1000" defaultValue="1" placeholder="迁移权重" required /><div className="flex items-center gap-2 rounded-md border border-input px-3 text-sm"><input id="browser_text_send" name="browser_text_send" type="checkbox" defaultChecked /><label htmlFor="browser_text_send">文本发送</label></div><Button type="submit" disabled={pending}>{pending ? '创建中…' : '创建方案'}</Button></form>
}

export function BatchCreateForm({ plans, pending, onSubmit }: { plans: Plan[]; pending: boolean; onSubmit: (value: components['schemas']['AdminCreateCardBatchRequest']) => void }) {
  return <form className="grid gap-3 md:grid-cols-[1.2fr_1fr_0.7fr_0.7fr_1.4fr_1.4fr_auto]" onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); const notBeforeValue = String(form.get('redeem_not_before') ?? ''); const beforeValue = String(form.get('redeem_before') ?? ''); onSubmit({ plan_id: String(form.get('plan_id') ?? ''), name: String(form.get('name') ?? '').trim(), duration_days: Number(form.get('duration_days') ?? 0), quantity: Number(form.get('quantity') ?? 0), redeem_not_before: notBeforeValue ? new Date(notBeforeValue).toISOString() : null, redeem_before: beforeValue ? new Date(beforeValue).toISOString() : null, note: String(form.get('note') ?? '').trim() }) }}><select name="plan_id" aria-label="权益方案" className="h-9 rounded-md border border-input bg-transparent px-3 text-sm" required defaultValue=""><option value="" disabled>选择权益方案</option>{plans.filter((plan) => plan.status === 'active').map((plan) => <option key={plan.id} value={plan.id}>{plan.name} · {plan.code}</option>)}</select><Input name="name" aria-label="批次名称" placeholder="批次名称" required /><Input name="duration_days" aria-label="有效天数" type="number" min="1" max="3660" placeholder="天数" required /><Input name="quantity" aria-label="生成数量" type="number" min="1" max="1000" placeholder="数量" required /><Input name="redeem_not_before" aria-label="兑换开始时间" type="datetime-local" /><Input name="redeem_before" aria-label="兑换截止时间" type="datetime-local" /><Input name="note" aria-label="批次备注" placeholder="备注（可选）" /><Button type="submit" disabled={pending || plans.every((plan) => plan.status !== 'active')}>{pending ? '生成中…' : '生成批次'}</Button></form>
}

function formatRate(value: number) {
  return `${Math.round(value * 100)}%`
}

function statusLabel(status: string) {
  return status === 'active' ? '生效中' : status === 'scheduled' ? '待生效' : status === 'expired' ? '已过期' : '已撤销'
}

function statusVariant(status: string): 'success' | 'secondary' | 'muted' | 'destructive' {
  return status === 'active' ? 'success' : status === 'revoked' ? 'destructive' : status === 'scheduled' ? 'secondary' : 'muted'
}

function formatDate(value: string | null | undefined) {
  if (!value) return '立即'
  return new Intl.DateTimeFormat('zh-CN', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value))
}
