import type { components } from '@douyin-keeper/sdk-ts'
import { Link } from '@tanstack/react-router'
import { Badge, Button, DateTimePicker, Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger, Input, Label, Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@douyin-keeper/ui-web'
import { Plus } from 'lucide-react'
import { useState, type FormEvent } from 'react'

import { SelectField } from '@/components/select-field'

type Plan = components['schemas']['AdminEntitlementPlan']
type Batch = components['schemas']['AdminCardBatch']
type Redemption = components['schemas']['AdminRedemption']
type CardCode = components['schemas']['AdminCardCode']

export function AdminPlanTable({ plans, pendingPlanId, onDisable }: { plans: Plan[]; pendingPlanId?: string; onDisable: (id: string) => void }) {
  return <div className="overflow-x-auto rounded-lg border bg-card"><Table><TableHeader><TableRow><TableHead className="pl-5">方案</TableHead><TableHead>配额</TableHead><TableHead>迁移权重</TableHead><TableHead>功能</TableHead><TableHead>状态</TableHead><TableHead className="pr-5">操作</TableHead></TableRow></TableHeader><TableBody>{plans.map((plan) => <TableRow key={plan.id}><TableCell className="min-w-48 pl-5"><div className="font-medium">{plan.name}</div><div className="mt-1 text-xs text-muted-foreground">{plan.code}</div></TableCell><TableCell className="min-w-48 text-sm"><div>账号 {plan.account_quota} · 任务 {plan.task_quota}</div><div className="mt-1 text-xs text-muted-foreground">每日发送 {plan.daily_send_quota}</div></TableCell><TableCell className="min-w-24 text-sm"><div className="font-medium">{plan.migration_weight}</div><div className="mt-1 text-xs text-muted-foreground">能力单位/天</div></TableCell><TableCell className="min-w-52"><div className="flex max-w-64 flex-wrap gap-1.5">{Object.entries(plan.features ?? {}).filter(([, enabled]) => enabled).slice(0, 4).map(([feature]) => <Badge key={feature} variant="muted">{feature}</Badge>)}{!Object.values(plan.features ?? {}).some(Boolean) && <span className="text-sm text-muted-foreground">无额外功能</span>}</div></TableCell><TableCell className="min-w-24"><Badge variant={plan.status === 'active' ? 'success' : 'muted'}>{plan.status === 'active' ? '启用' : '已停用'}</Badge></TableCell><TableCell className="min-w-24 pr-5">{plan.status === 'active' ? <Button size="sm" variant="ghost" disabled={pendingPlanId === plan.id} onClick={() => onDisable(plan.id)}>{pendingPlanId === plan.id ? '处理中…' : '停用'}</Button> : <span className="text-sm text-muted-foreground">—</span>}</TableCell></TableRow>)}</TableBody></Table></div>
}

export function AdminBatchTable({ batches, pendingBatchId, onDisable }: { batches: Batch[]; pendingBatchId?: string; onDisable: (id: string) => void }) {
  return <div className="overflow-x-auto rounded-lg border bg-card"><Table><TableHeader><TableRow><TableHead className="pl-5">批次 / 方案</TableHead><TableHead>使用情况</TableHead><TableHead>兑换窗口</TableHead><TableHead>创建人</TableHead><TableHead>状态</TableHead><TableHead className="pr-5">操作</TableHead></TableRow></TableHeader><TableBody>{batches.map((batch) => <TableRow key={batch.id}><TableCell className="min-w-52 pl-5"><Link to="/admin/entitlement/batches/$batchId" params={{ batchId: batch.id }} className="font-medium hover:underline">{batch.name}</Link><div className="mt-1 text-xs text-muted-foreground">{batch.plan_name} · {batch.duration_days} 天</div></TableCell><TableCell className="min-w-48 text-sm"><div>已兑换 {batch.redeemed_count} / {batch.quantity}</div><div className="mt-1 text-xs text-muted-foreground">未使用 {batch.unused_count} · 撤销 {batch.revoked_count} · {formatRate(batch.redemption_rate)}</div></TableCell><TableCell className="min-w-48 text-sm"><div>{formatDate(batch.redeem_not_before)} 起</div><div className="mt-1 text-xs text-muted-foreground">{batch.redeem_before ? `截止 ${formatDate(batch.redeem_before)}` : '无截止时间'}</div></TableCell><TableCell className="min-w-28 text-sm">{batch.created_by_display_name}</TableCell><TableCell className="min-w-24"><Badge variant={batch.status === 'active' ? 'success' : 'muted'}>{batch.status === 'active' ? '启用' : '已停用'}</Badge></TableCell><TableCell className="min-w-24 pr-5">{batch.status === 'active' ? <Button size="sm" variant="ghost" disabled={pendingBatchId === batch.id} onClick={() => onDisable(batch.id)}>{pendingBatchId === batch.id ? '处理中…' : '停用'}</Button> : <span className="text-sm text-muted-foreground">—</span>}</TableCell></TableRow>)}</TableBody></Table></div>
}

export function AdminRedemptionTable({ redemptions }: { redemptions: Redemption[] }) {
  return <div className="overflow-x-auto rounded-lg border bg-card"><Table><TableHeader><TableRow><TableHead className="pl-5">用户</TableHead><TableHead>方案 / 来源</TableHead><TableHead>有效期</TableHead><TableHead>卡密指纹</TableHead><TableHead className="pr-5">状态</TableHead></TableRow></TableHeader><TableBody>{redemptions.map((item) => <TableRow key={item.id}><TableCell className="min-w-40 pl-5"><div className="font-medium">{item.user_display_name}</div><div className="mt-1 max-w-44 truncate text-xs text-muted-foreground" title={item.user_id}>{item.user_id}</div></TableCell><TableCell className="min-w-36"><div className="font-medium">{item.plan_name}</div><div className="mt-1 text-xs text-muted-foreground">{item.source_type === 'card' ? '卡密兑换' : '管理员授权'} · {item.plan_code}</div></TableCell><TableCell className="min-w-48 text-sm"><div>{formatDate(item.starts_at)} —</div><div className="mt-1 text-xs text-muted-foreground">{formatDate(item.expires_at)}</div></TableCell><TableCell className="min-w-32 font-mono text-xs text-muted-foreground">{item.code_fingerprint ?? '—'}</TableCell><TableCell className="min-w-32 pr-5"><Badge variant={statusVariant(item.status)}>{statusLabel(item.status)}</Badge>{item.revoke_reason && <div className="mt-1 max-w-40 truncate text-xs text-muted-foreground" title={item.revoke_reason}>原因：{item.revoke_reason}</div>}</TableCell></TableRow>)}</TableBody></Table></div>
}

export function AdminUserGrantTable({ grants, pendingGrantId, onRevoke }: { grants: Redemption[]; pendingGrantId?: string; onRevoke: (id: string, reason: string) => void }) {
  return <div className="overflow-x-auto rounded-lg border bg-card"><Table><TableHeader><TableRow><TableHead className="pl-5">方案 / 来源</TableHead><TableHead>有效期</TableHead><TableHead>状态</TableHead><TableHead>卡密指纹</TableHead><TableHead className="pr-5">操作</TableHead></TableRow></TableHeader><TableBody>{grants.map((item) => <TableRow key={item.id}><TableCell className="min-w-40 pl-5"><div className="font-medium">{item.plan_name}</div><div className="mt-1 text-xs text-muted-foreground">{item.source_type === 'card' ? '卡密兑换' : '管理员授权'} · {item.plan_code}</div></TableCell><TableCell className="min-w-48 text-sm"><div>{formatDate(item.starts_at)} —</div><div className="mt-1 text-xs text-muted-foreground">{formatDate(item.expires_at)}</div></TableCell><TableCell className="min-w-28"><Badge variant={statusVariant(item.status)}>{statusLabel(item.status)}</Badge>{item.revoke_reason && <div className="mt-1 max-w-36 truncate text-xs text-muted-foreground" title={item.revoke_reason}>{item.revoke_reason}</div>}</TableCell><TableCell className="min-w-36 font-mono text-xs text-muted-foreground">{item.code_fingerprint ?? '—'}</TableCell><TableCell className="min-w-32 pr-5">{item.status !== 'revoked' && item.status !== 'expired' ? <RevokeDialog label="撤销授权" pending={pendingGrantId === item.id} onSubmit={(reason) => onRevoke(item.id, reason)} /> : <span className="text-sm text-muted-foreground">—</span>}</TableCell></TableRow>)}</TableBody></Table></div>
}

export function AdminCardCodeTable({ codes, pendingCodeId, onRevoke }: { codes: CardCode[]; pendingCodeId?: number; onRevoke: (id: number, reason: string) => void }) {
  return <div className="overflow-x-auto rounded-lg border bg-card"><Table><TableHeader><TableRow><TableHead className="pl-5">卡密指纹</TableHead><TableHead>状态</TableHead><TableHead>时间</TableHead><TableHead className="pr-5">操作</TableHead></TableRow></TableHeader><TableBody>{codes.map((item) => <TableRow key={item.id}><TableCell className="min-w-48 pl-5 font-mono text-xs">{item.code_fingerprint}</TableCell><TableCell className="min-w-24"><Badge variant={item.status === 'unused' ? 'secondary' : item.status === 'redeemed' ? 'success' : 'muted'}>{item.status === 'unused' ? '未使用' : item.status === 'redeemed' ? '已兑换' : '已撤销'}</Badge></TableCell><TableCell className="min-w-48 text-sm"><div>创建 {formatDate(item.created_at)}</div><div className="mt-1 text-xs text-muted-foreground">{item.redeemed_at ? `兑换 ${formatDate(item.redeemed_at)}` : item.revoked_at ? `撤销 ${formatDate(item.revoked_at)}` : '尚未使用'}</div></TableCell><TableCell className="min-w-32 pr-5">{item.status === 'unused' ? <RevokeDialog label="撤销卡密" pending={pendingCodeId === item.id} onSubmit={(reason) => onRevoke(item.id, reason)} /> : <span className="text-sm text-muted-foreground">—</span>}</TableCell></TableRow>)}</TableBody></Table></div>
}

export function AdminGrantCreateForm({ plans, pending, disabled, onSubmit }: { plans: Plan[]; pending: boolean; disabled?: boolean; onSubmit: (value: components['schemas']['AdminCreateEntitlementGrantRequest']) => void }) { const [open, setOpen] = useState(false); const [planId, setPlanId] = useState(''); const activePlans = plans.filter((plan) => plan.status === 'active'); function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); onSubmit({ plan_id: planId, duration_days: Number(form.get('duration_days') ?? 0) }); setOpen(false) } return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button disabled={disabled || activePlans.length === 0}><Plus />人工授权</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>人工授权</DialogTitle><DialogDescription>选择权益方案并设置授权天数，授权会写入用户审计记录。</DialogDescription></DialogHeader><form onSubmit={submit}><div className="grid gap-4 px-6 py-6"><SelectField id="admin-grant-plan" label="权益方案" value={planId} onChange={setPlanId} disabled={disabled} placeholder="选择权益方案" options={activePlans.map((plan) => ({ value: plan.id, label: `${plan.name} · ${plan.code}` }))} /><div className="space-y-1.5"><Label htmlFor="admin-grant-duration">授权天数</Label><Input id="admin-grant-duration" name="duration_days" type="number" min="1" max="3660" placeholder="例如 30" required disabled={disabled} /></div></div><DialogFooter><Button type="button" variant="outline" onClick={() => setOpen(false)}>取消</Button><Button type="submit" disabled={disabled || pending || activePlans.length === 0 || !planId}>{pending ? '授权中…' : '确认授权'}</Button></DialogFooter></form></DialogContent></Dialog> }

export function PlanCreateForm({ pending, onSubmit }: { pending: boolean; onSubmit: (value: components['schemas']['AdminCreateEntitlementPlanRequest']) => void }) {
  const [open, setOpen] = useState(false)
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); onSubmit({ code: String(form.get('code') ?? '').trim(), name: String(form.get('name') ?? '').trim(), account_quota: Number(form.get('account_quota') ?? 0), task_quota: Number(form.get('task_quota') ?? 0), daily_send_quota: Number(form.get('daily_send_quota') ?? 0), migration_weight: Number(form.get('migration_weight') ?? 1), features: { browser_text_send: form.get('browser_text_send') === 'on' } }); setOpen(false) }
  return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button variant="outline"><Plus />新建方案</Button></DialogTrigger><DialogContent className="max-w-2xl"><DialogHeader><DialogTitle>新建权益方案</DialogTitle><DialogDescription>定义账号、任务和每日发送额度；方案创建后仍可单独停用。</DialogDescription></DialogHeader><form onSubmit={submit}><div className="grid gap-4 px-6 py-6 sm:grid-cols-2"><div className="space-y-1.5"><Label htmlFor="plan-code">方案代码</Label><Input id="plan-code" name="code" placeholder="例如 standard" required /></div><div className="space-y-1.5"><Label htmlFor="plan-name">方案名称</Label><Input id="plan-name" name="name" placeholder="例如 标准版" required /></div><div className="space-y-1.5"><Label htmlFor="plan-account-quota">账号额度</Label><Input id="plan-account-quota" name="account_quota" type="number" min="0" placeholder="账号" required /></div><div className="space-y-1.5"><Label htmlFor="plan-task-quota">任务额度</Label><Input id="plan-task-quota" name="task_quota" type="number" min="0" placeholder="任务" required /></div><div className="space-y-1.5"><Label htmlFor="plan-daily-send">每日发送额度</Label><Input id="plan-daily-send" name="daily_send_quota" type="number" min="0" placeholder="每日发送" required /></div><div className="space-y-1.5"><Label htmlFor="plan-weight">迁移权重</Label><Input id="plan-weight" name="migration_weight" type="number" min="1" max="1000" defaultValue="1" required /></div><label className="flex items-center gap-2 rounded-lg border border-input px-3 py-2 text-sm sm:col-span-2"><input id="browser_text_send" name="browser_text_send" type="checkbox" defaultChecked />文本发送</label></div><DialogFooter><Button type="button" variant="outline" onClick={() => setOpen(false)}>取消</Button><Button type="submit" disabled={pending}>{pending ? '创建中…' : '创建方案'}</Button></DialogFooter></form></DialogContent></Dialog>
}

export function BatchCreateForm({ plans, pending, onSubmit }: { plans: Plan[]; pending: boolean; onSubmit: (value: components['schemas']['AdminCreateCardBatchRequest']) => void }) { const [open, setOpen] = useState(false); const [planId, setPlanId] = useState(''); const [notBefore, setNotBefore] = useState<Date>(); const [before, setBefore] = useState<Date>(); const activePlans = plans.filter((plan) => plan.status === 'active'); function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); onSubmit({ plan_id: planId, name: String(form.get('name') ?? '').trim(), duration_days: Number(form.get('duration_days') ?? 0), quantity: Number(form.get('quantity') ?? 0), redeem_not_before: notBefore?.toISOString() ?? null, redeem_before: before?.toISOString() ?? null, note: String(form.get('note') ?? '').trim() }); setOpen(false) } return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button variant="outline" disabled={activePlans.length === 0}><Plus />生成卡密批次</Button></DialogTrigger><DialogContent className="max-w-3xl"><DialogHeader><DialogTitle>生成卡密批次</DialogTitle><DialogDescription>明文卡密只在生成成功后显示一次，请在当前会话内下载并安全保存。</DialogDescription></DialogHeader><form onSubmit={submit}><div className="grid gap-4 px-6 py-6 sm:grid-cols-2"><SelectField id="admin-batch-plan" label="权益方案" value={planId} onChange={setPlanId} placeholder="选择权益方案" options={activePlans.map((plan) => ({ value: plan.id, label: `${plan.name} · ${plan.code}` }))} /><div className="space-y-1.5"><Label htmlFor="batch-name">批次名称</Label><Input id="batch-name" name="name" placeholder="例如 2026-08 内测批次" required /></div><div className="space-y-1.5"><Label htmlFor="batch-duration">有效天数</Label><Input id="batch-duration" name="duration_days" type="number" min="1" max="3660" placeholder="天数" required /></div><div className="space-y-1.5"><Label htmlFor="batch-quantity">生成数量</Label><Input id="batch-quantity" name="quantity" type="number" min="1" max="1000" placeholder="数量" required /></div><DateTimePicker id="redeem-not-before" value={notBefore} onChange={setNotBefore} placeholder="兑换开始时间" /><DateTimePicker id="redeem-before" value={before} onChange={setBefore} placeholder="兑换截止时间" /><div className="space-y-1.5 sm:col-span-2"><Label htmlFor="batch-note">备注（可选）</Label><Input id="batch-note" name="note" placeholder="记录本批次用途" /></div></div><DialogFooter><Button type="button" variant="outline" onClick={() => setOpen(false)}>取消</Button><Button type="submit" disabled={pending || activePlans.length === 0 || !planId}>{pending ? '生成中…' : '确认生成'}</Button></DialogFooter></form></DialogContent></Dialog> }

function RevokeDialog({ label, pending, onSubmit }: { label: string; pending: boolean; onSubmit: (reason: string) => void }) {
  const [open, setOpen] = useState(false)
  const [reason, setReason] = useState('')
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const normalized = reason.trim(); if (!normalized) return; onSubmit(normalized); setReason(''); setOpen(false) }
  return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button size="sm" variant="ghost" disabled={pending}>{pending ? '处理中…' : label}</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>{label}</DialogTitle><DialogDescription>请输入原因。撤销后该记录会保留在审计时间线中，不能恢复。</DialogDescription></DialogHeader><form onSubmit={submit}><div className="px-6 py-6"><Label htmlFor="revoke-reason">撤销原因</Label><Input id="revoke-reason" className="mt-2" value={reason} onChange={(event) => setReason(event.target.value)} placeholder="例如：测试批次作废" autoFocus required /></div><DialogFooter><Button type="button" variant="outline" onClick={() => setOpen(false)}>取消</Button><Button type="submit" variant="destructive" disabled={!reason.trim() || pending}>确认撤销</Button></DialogFooter></form></DialogContent></Dialog>
}

function formatRate(value: number | null | undefined) {
  return `${Math.round(Number(value ?? 0) * 100)}%`
}

function statusLabel(status: string) {
  return status === 'active' ? '生效中' : status === 'scheduled' ? '待生效' : status === 'expired' ? '已过期' : '已撤销'
}

function statusVariant(status: string): 'success' | 'secondary' | 'muted' | 'destructive' {
  return status === 'active' ? 'success' : status === 'revoked' ? 'destructive' : status === 'scheduled' ? 'secondary' : 'muted'
}

function formatDate(value: string | null | undefined) {
  if (!value) return '立即'
  const date = new Date(value)
  return Number.isNaN(date.getTime()) ? '暂无' : new Intl.DateTimeFormat('zh-CN', { dateStyle: 'medium', timeStyle: 'short' }).format(date)
}
