/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAdminUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAdminAccounts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/workers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAdminRuntime"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/adapters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAdminAdapters"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/adapters/{adapter}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateAdminAdapter"];
        trace?: never;
    };
    "/admin/risks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAdminRisks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/audit-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAdminAuditLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAccounts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/bindings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createAccountBinding"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/{accountId}/session-check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["checkAccountSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/{accountId}/friends-sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["syncAccountFriends"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/{accountId}/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAccountCapabilities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/{accountId}/friends": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listFriends"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/friends/{friendId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateFriend"];
        trace?: never;
    };
    "/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listTasks"];
        put?: never;
        post: operations["createTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{taskId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteTask"];
        options?: never;
        head?: never;
        patch: operations["updateTask"];
        trace?: never;
    };
    "/tasks/{taskId}/run-now": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["runTaskNow"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/send-intents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listSendIntents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/send-jobs/{jobId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSendJob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{jobId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getJob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{jobId}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Replay and stream append-only job events as Server-Sent Events. */
        get: operations["streamJobEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{jobId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["cancelJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["refreshSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logoutAll"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/link-codes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createWechatLinkCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/wechat-mini/link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["linkWechatMini"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/wechat-mini/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["loginWechatMini"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/entitlement": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMyEntitlement"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entitlements/redeem": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["redeemCardCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entitlements/redemptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listMyEntitlementGrants"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        User: {
            /** Format: uuid */
            id: string;
            display_name: string;
            /** @enum {string} */
            role: "user" | "admin";
        };
        AdminUser: {
            /** Format: uuid */
            id: string;
            display_name: string;
            /** @enum {string} */
            role: "user" | "admin";
            /** @enum {string} */
            status: "active" | "disabled";
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            last_login_at?: string | null;
            account_count: number;
            task_count: number;
            /** Format: date-time */
            entitlement_expires_at?: string | null;
        };
        AdminAccountCapability: {
            name: string;
            /** @enum {string} */
            status: "available" | "degraded" | "unavailable" | "unknown";
            adapter?: string | null;
            error_code?: string | null;
            /** Format: date-time */
            checked_at: string;
        };
        AdminRecentError: {
            category: string;
            code: string;
            /** @enum {string} */
            severity: "info" | "warning" | "critical";
            source_adapter?: string | null;
            /** Format: date-time */
            created_at: string;
        };
        AdminAccount: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            owner_id: string;
            owner_display_name: string;
            platform_user_id?: string | null;
            nickname: string;
            /** @enum {string} */
            binding_status: "unbound" | "binding" | "bound" | "released";
            /** @enum {string} */
            session_status: "unknown" | "valid" | "expired" | "challenge_required";
            /** @enum {string} */
            risk_status: "normal" | "cooling_down" | "paused";
            /** Format: date-time */
            paused_at?: string | null;
            /** Format: date-time */
            cooldown_until?: string | null;
            /** Format: date-time */
            last_session_check_at?: string | null;
            /** Format: date-time */
            last_friend_sync_at?: string | null;
            capabilities: components["schemas"]["AdminAccountCapability"][];
            today_send_succeeded: number;
            today_send_failed: number;
            latest_error?: components["schemas"]["AdminRecentError"] | null;
        };
        AdminWorkerPool: {
            name: string;
            online: boolean;
            /** Format: date-time */
            started_at?: string | null;
            /** Format: date-time */
            last_observed_at?: string | null;
            active_workers: number;
            concurrency: number;
            version?: string | null;
            playwright_version?: string | null;
            protocol_version?: string | null;
        };
        AdminQueue: {
            name: string;
            pool: string;
            pending: number;
            active: number;
            scheduled: number;
            retry: number;
            failed: number;
            processed: number;
            latency_seconds: number;
            paused: boolean;
        };
        AdminRuntime: {
            /** Format: date-time */
            observed_at: string;
            api_version?: string | null;
            worker_version?: string | null;
            playwright_sidecar_version?: string | null;
            protocol_sidecar_version?: string | null;
            pools: components["schemas"]["AdminWorkerPool"][];
            queues: components["schemas"]["AdminQueue"][];
            running_jobs: number;
            failed_jobs_24h: number;
            browser_slots_used: number;
            browser_slots_limit: number;
            scheduler_online: boolean;
            /** Format: date-time */
            scheduler_leader_expires_at?: string | null;
        };
        AdminAdapter: {
            name: string;
            /** @enum {string} */
            status: "healthy" | "degraded" | "down" | "disabled" | "unknown";
            enabled: boolean;
            executable: boolean;
            version?: string | null;
            error_code?: string | null;
            failure_count: number;
            /** Format: date-time */
            circuit_open_until?: string | null;
            /** Format: date-time */
            checked_at?: string | null;
        };
        AdminRisk: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            account_id: string;
            owner_display_name: string;
            nickname: string;
            /** @enum {string} */
            category: "AUTH" | "PLATFORM" | "PROTOCOL" | "BROWSER" | "NETWORK" | "DATA";
            code: string;
            /** @enum {string} */
            severity: "info" | "warning" | "critical";
            source_adapter?: string | null;
            action?: string | null;
            /** Format: date-time */
            cooldown_until?: string | null;
            /** Format: date-time */
            created_at: string;
        };
        AdminAuditLog: {
            /** Format: int64 */
            id: number;
            actor_display_name?: string | null;
            action: string;
            resource_type: string;
            resource_id?: string | null;
            has_detail: boolean;
            /** Format: date-time */
            created_at: string;
        };
        Account: {
            /** Format: uuid */
            id: string;
            nickname: string;
            /** Format: uri */
            avatar_url?: string | null;
            /** @enum {string} */
            binding_status: "unbound" | "binding" | "bound" | "released";
            /** @enum {string} */
            session_status: "unknown" | "valid" | "expired" | "challenge_required";
            /** @enum {string} */
            risk_status: "normal" | "cooling_down" | "paused";
            /** Format: date-time */
            last_session_check_at?: string | null;
            /** Format: date-time */
            last_friend_sync_at?: string | null;
            /** Format: date-time */
            paused_at?: string | null;
        };
        Capability: {
            capability: string;
            /** @enum {string} */
            status: "available" | "degraded" | "unavailable" | "unknown";
            adapter?: string | null;
            error_code?: string | null;
            /** Format: date-time */
            checked_at: string;
        };
        Friend: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            platform_identity_status: "pending" | "resolved" | "ambiguous" | "missing";
            display_name: string;
            nickname?: string;
            short_id?: string | null;
            /** Format: uri */
            avatar_url?: string | null;
            streak_days: number;
            has_conversation: boolean;
            spark_enabled: boolean;
            /** Format: date-time */
            last_sent_at?: string | null;
        };
        SparkTask: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            account_id: string;
            /** Format: uuid */
            friend_id: string;
            /** Format: uuid */
            task_id?: string | null;
            enabled: boolean;
            timezone: string;
            window_start: string;
            window_end: string;
            message: {
                /** @enum {string} */
                kind: "text" | "sticker";
                body?: string | null;
            };
            allow_first_message?: boolean;
        };
        CreateTaskRequest: {
            /** Format: uuid */
            account_id: string;
            /** Format: uuid */
            friend_id: string;
            enabled: boolean;
            timezone: string;
            window_start: string;
            window_end: string;
            message: {
                /** @enum {string} */
                kind: "text";
                body?: string;
            };
            /** @default false */
            allow_first_message: boolean;
        };
        JobRef: {
            /** Format: uuid */
            job_id: string;
        };
        HistoryAccount: {
            /** Format: uuid */
            id: string;
            nickname: string;
        };
        HistoryFriend: {
            /** Format: uuid */
            id: string;
            display_name: string;
        };
        HistoryTask: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            message_kind: "text" | "sticker";
            body?: string | null;
        };
        HistoryJob: {
            /** Format: uuid */
            id: string;
            adapter?: string | null;
            attempt: number;
            /** @enum {string} */
            status: "queued" | "running" | "succeeded" | "failed" | "cancelled";
            error_code?: string | null;
        };
        SendIntent: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            intent_type: "scheduled" | "manual";
            /** Format: uuid */
            account_id: string;
            /** Format: uuid */
            friend_id: string;
            /** Format: uuid */
            task_id?: string | null;
            task: components["schemas"]["HistoryTask"] | null;
            local_date?: string | null;
            /** @enum {string} */
            status: "pending" | "queued" | "running" | "retry_wait" | "succeeded" | "failed" | "skipped" | "cancelled";
            error_code?: string | null;
            /** Format: date-time */
            scheduled_at: string;
            /** Format: date-time */
            created_at: string;
            account: components["schemas"]["HistoryAccount"];
            friend: components["schemas"]["HistoryFriend"];
            latest_job: components["schemas"]["HistoryJob"] | null;
        };
        SendJob: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            status: "queued" | "running" | "succeeded" | "failed" | "cancelled";
            attempt: number;
            selected_adapter?: string | null;
            error_code?: string | null;
            retryable: boolean;
            /** @description Present for diagnostics but intentionally hidden in the web UI. */
            platform_message_id?: string | null;
            /** Format: date-time */
            started_at?: string | null;
            /** Format: date-time */
            finished_at?: string | null;
        };
        Job: {
            /** Format: uuid */
            id: string;
            type: string;
            /** @enum {string} */
            status: "queued" | "running" | "waiting_user" | "succeeded" | "failed" | "cancelled";
            cancelable: boolean;
            error_code?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            started_at?: string | null;
            /** Format: date-time */
            finished_at?: string | null;
            /** Format: date-time */
            cancel_requested_at?: string | null;
        };
        ApiError: {
            error: {
                code: string;
                message: string;
                request_id: string;
                details?: Record<string, never>;
            };
        };
        RegisterRequest: {
            username: string;
            password: string;
        };
        LoginRequest: {
            username: string;
            password: string;
        };
        AuthResponse: {
            access_token: string;
            expires_in: number;
            /** @description Returned for mini clients; web normally receives an HttpOnly refresh cookie. */
            refresh_token?: string | null;
            user: components["schemas"]["User"];
        };
        LinkCode: {
            code: string;
            /** Format: date-time */
            expires_at: string;
        };
        WechatLinkRequest: {
            wechat_code: string;
            link_code: string;
        };
        WechatLoginRequest: {
            wechat_code: string;
        };
        EffectiveEntitlement: {
            active: boolean;
            /** Format: uuid */
            grant_id?: string | null;
            plan_code?: string | null;
            /** Format: date-time */
            starts_at?: string | null;
            /** Format: date-time */
            expires_at?: string | null;
            account_quota?: number;
            task_quota?: number;
            daily_send_quota?: number;
            features?: {
                [key: string]: boolean;
            };
            usage?: {
                accounts_used?: number;
                tasks_used?: number;
                daily_send_reserved?: number;
                /** Format: date */
                quota_local_date?: string | null;
            };
        };
        RedeemCardRequest: {
            code: string;
        };
        EntitlementGrant: {
            /** Format: uuid */
            id: string;
            plan_code?: string;
            /** @enum {string} */
            source_type: "card" | "admin";
            /** Format: date-time */
            starts_at: string;
            /** Format: date-time */
            expires_at: string;
            /** Format: date-time */
            revoked_at?: string | null;
        };
        RedeemResult: {
            grant: components["schemas"]["EntitlementGrant"];
            entitlement: components["schemas"]["EffectiveEntitlement"];
        };
    };
    responses: {
        /** @description Not authenticated */
        Unauthenticated: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description Resource state conflict */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
    };
    parameters: {
        AccountId: string;
        Limit: number;
        Cursor: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthenticated"];
        };
    };
    listAdminUsers: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Administrator user summaries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["AdminUser"][];
                        next_cursor: string | null;
                    };
                };
            };
        };
    };
    listAdminAccounts: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Administrator account summaries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["AdminAccount"][];
                        next_cursor: string | null;
                    };
                };
            };
        };
    };
    getAdminRuntime: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Administrator worker and queue runtime summary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminRuntime"];
                };
            };
        };
    };
    listAdminAdapters: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Administrator adapter health summaries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["AdminAdapter"][];
                    };
                };
            };
        };
    };
    updateAdminAdapter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                adapter: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    enabled: boolean;
                };
            };
        };
        responses: {
            /** @description Updated adapter state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminAdapter"];
                };
            };
        };
    };
    listAdminRisks: {
        parameters: {
            query?: {
                category?: "AUTH" | "PLATFORM" | "PROTOCOL" | "BROWSER" | "NETWORK" | "DATA";
                severity?: "info" | "warning" | "critical";
                code?: string;
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Administrator risk event summaries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["AdminRisk"][];
                        next_cursor: string | null;
                    };
                };
            };
        };
    };
    listAdminAuditLogs: {
        parameters: {
            query?: {
                action?: string;
                resource_type?: string;
                actor?: string;
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Administrator audit log summaries without raw detail JSON */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["AdminAuditLog"][];
                        next_cursor: string | null;
                    };
                };
            };
        };
    };
    listAccounts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accounts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Account"][];
                        next_cursor: string | null;
                    };
                };
            };
        };
    };
    createAccountBinding: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    method: "qr";
                };
            };
        };
        responses: {
            /** @description Binding job created */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRef"];
                };
            };
        };
    };
    checkAccountSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                accountId: components["parameters"]["AccountId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Job created */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRef"];
                };
            };
        };
    };
    syncAccountFriends: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                accountId: components["parameters"]["AccountId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Job created */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRef"];
                };
            };
        };
    };
    getAccountCapabilities: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                accountId: components["parameters"]["AccountId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Capability snapshot */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Capability"][];
                    };
                };
            };
        };
    };
    listFriends: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path: {
                accountId: components["parameters"]["AccountId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Friends */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Friend"][];
                        next_cursor: string | null;
                    };
                };
            };
        };
    };
    updateFriend: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                friendId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    spark_enabled?: boolean;
                };
            };
        };
        responses: {
            /** @description Updated friend */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Friend"];
                };
            };
            409: components["responses"]["Conflict"];
        };
    };
    listTasks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tasks */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["SparkTask"][];
                        next_cursor: string | null;
                    };
                };
            };
        };
    };
    createTask: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTaskRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SparkTask"];
                };
            };
        };
    };
    deleteTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taskId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taskId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    enabled?: boolean;
                    timezone?: string;
                    window_start?: string;
                    window_end?: string;
                    message?: {
                        /** @enum {string} */
                        kind: "text" | "sticker";
                        body?: string | null;
                    };
                    allow_first_message?: boolean;
                };
            };
        };
        responses: {
            /** @description Updated task */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SparkTask"];
                };
            };
            409: components["responses"]["Conflict"];
        };
    };
    runTaskNow: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                taskId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Send queued */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        intent_id: string;
                        /** Format: uuid */
                        job_id: string;
                        /** @enum {string} */
                        status: "queued";
                    };
                };
            };
        };
    };
    listSendIntents: {
        parameters: {
            query?: {
                account_id?: string;
                friend_id?: string;
                status?: "pending" | "queued" | "running" | "retry_wait" | "succeeded" | "failed" | "skipped" | "cancelled";
                from?: string;
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Send history */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["SendIntent"][];
                        next_cursor: string | null;
                    };
                };
            };
        };
    };
    getSendJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Send job diagnostics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SendJob"];
                };
            };
        };
    };
    getJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Job */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
        };
    };
    streamJobEvents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Job event stream. Each SSE frame carries event, id, and a JSON payload in data. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
        };
    };
    cancelJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cancellation requested */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: components["responses"]["Conflict"];
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Registered */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            409: components["responses"]["Conflict"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Authenticated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            401: components["responses"]["Unauthenticated"];
        };
    };
    refreshSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @description Required for mini clients; web uses HttpOnly refresh cookie. */
                    refresh_token?: string | null;
                };
            };
        };
        responses: {
            /** @description Session rotated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            401: components["responses"]["Unauthenticated"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current session revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    logoutAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All sessions revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createWechatLinkCode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One-time link code */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LinkCode"];
                };
            };
        };
    };
    linkWechatMini: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WechatLinkRequest"];
            };
        };
        responses: {
            /** @description Linked and authenticated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            409: components["responses"]["Conflict"];
        };
    };
    loginWechatMini: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WechatLoginRequest"];
            };
        };
        responses: {
            /** @description Authenticated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            409: components["responses"]["Conflict"];
        };
    };
    getMyEntitlement: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Effective entitlement */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EffectiveEntitlement"];
                };
            };
        };
    };
    redeemCardCode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RedeemCardRequest"];
            };
        };
        responses: {
            /** @description Redeemed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RedeemResult"];
                };
            };
            409: components["responses"]["Conflict"];
        };
    };
    listMyEntitlementGrants: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Grants */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["EntitlementGrant"][];
                    };
                };
            };
        };
    };
}
